server:
  port: ${ARCHIVE_SERVICE:8084}
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/mydb
  application:
    name: kanban-service
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    fetchRegistry: true
    registerWithEureka: true