server:
  port: 8083
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/mydb
  application:
    name: task-service
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    fetchRegistry: true
    registerWithEureka: true